create table order_(
    id bigint generated by default as identity primary key ,
    created_by varchar(100),
    book_id bigint references book(id) on delete set null ,
    status varchar(20) not null,
    create_at date
);