drop table genre;

create table if not exists genre
(
    id   bigint primary key generated by default as identity,
    name varchar(100) not null
);

create table if not exists genre_book
(
    genre_id bigint references genre (id) on delete set null,
    book_id   bigint references book (id) on delete set null,
    primary key (genre_id, book_id)
);

create table if not exists genre_author
(
    genre_id bigint references genre (id) on delete set null,
    author_id   bigint references author (id) on delete set null,
    primary key (genre_id, author_id)
);